### ISSUE TITLE
Set default color for the action buttons

### ISSUE THREAD

**Issue by slowmove** [SeunLanLege/vscode-action-buttons#1]
Since you can have different color themes on the entire chrome of the application, it would be nice to be able to set a default color for the action buttons.
If you just use the default setting, reading scripts from package.json, you can't tweak these colors as of now.

<img width="363" alt="skarmavbild 2017-07-10 kl 12 11 28" src="https://user-images.githubusercontent.com/624182/28013323-f1b39752-6568-11e7-9a23-417aeb06350a.png">

**Comment by SeunLanLege** [comment]
hmm, i'll add a default color in the settings

**Comment by SeunLanLege** [comment]
Added
