### ISSUE TITLE
Remove/Hide 'Refresh Action Buttons' Button

### ISSUE THREAD

**Issue by qu1ckdry** [seunlanlege/vscode-action-buttons#12]
Hey, 

Is it possible to remove or hide the 'Refresh Action Buttons' button? It takes up way too much space!

Thanks,

**Comment by seunlanlege** [comment]
will attend to this today.

**Comment by phreakadelle2k** [comment]
At least it could be much shorter...

**Comment by qu1ckdry** [comment]
So for what it's worth... I locally replaced the string "Refresh Action Buttons" with "↻" in the init file. I'm not sure how portable this solution would be (would all platforms render this symbol?) so I won't make a pull request or anything but I thought I'd share my hack!

**Comment by seunlanlege** [comment]
@qu1ckdry please send a PR

**Comment by iansan5653** [comment]
Why don't you turn it into a command in the command pallete instead? Or just check for a settings change event.
