### ISSUE TITLE
Hide tasks from package.json

### ISSUE THREAD

**Issue by mackelito** [seunlanlege/vscode-action-buttons#13]
Really nice to see that it picks up stuff in package.json but we have lots of tasks there and would like to be able to hide some of them :)

**Comment by seunlanlege** [comment]
will add an option that disables picking up scripts from package.json

**Comment by mackelito** [comment]
Just to be clear... Would like a ignore feature or something like that. 🙂

**Comment by phreakadelle2k** [comment]
Maybe those could also be put into some kind of dropdown menu...

**Comment by mann-david** [comment]
+1

**Comment by aikodeio** [comment]
+1 !!!! :+1:
