### ISSUE TITLE
how to add icon on a button

### ISSUE THREAD

**Issue by Kush5900** [seunlanlege/vscode-action-buttons#16]
i'm wondering if there is a way to add icons on buttons words

**Comment by seunlanlege** [comment]
You can use emojis

**Comment by Kush5900** [comment]
How Exactly?

**Comment by kaipaysen** [comment]
Just like you're using it anywhere else: 
![image](https://user-images.githubusercontent.com/8957069/60324519-4c38c600-9985-11e9-9dc0-25d7f2ea0cfb.png)
