### ISSUE TITLE
Is it possible to use templates like ${file}?

### ISSUE THREAD

**Issue by MasterGroosha** [seunlanlege/vscode-action-buttons#19]
Currently my `settings.json` looks like:
```
{
    "actionButtons": {
        "commands": [
            {
                "name": "Go Run",
                "color": "Red",
                "singleInstance": true,
                "command": "go run ${file}"
            }
        ]
    },
}
```

Unfortunately, when I run this task, it tries to execute `go run ${file}`, not `go run <currently open file>`, though `${file}` template works fine in VSCode's tasks.
Is it possible to add support for such templates in this extension?

**Comment by seunlanlege** [comment]
Actually, yes it should be possible

**Comment by MasterGroosha** [comment]
The problem is that doesn't work :(
Does it work for you?
