### ISSUE TITLE
Adding parameters

### ISSUE THREAD

**Issue by Atnaize** [seunlanlege/vscode-action-buttons#36]
I have this kind of command
```
{
                "name": "🧪 ",
                "color": "white",
                "command": "php artisan tenancy:tinker --website_id=1",
},
```
But I would like to type the "1" in the terminal instead of hard-coding it in the settings. Is it possible?

**Comment by lisunovdv** [comment]
> I have this kind of command
> 
> ```
> {
>                 "name": "🧪 ",
>                 "color": "white",
>                 "command": "php artisan tenancy:tinker --website_id=1",
> },
> ```
> 
> But I would like to type the "1" in the terminal instead of hard-coding it in the settings. Is it possible?

You can use ${selectedText} for this: https://github.com/seunlanlege/vscode-action-buttons/blob/master/src/init.ts#L88

**Comment by Atnaize** [comment]
Thanks !
