### ISSUE TITLE
Add Terminal silent mode

### ISSUE THREAD

**Issue by lisunovdv** [seunlanlege/vscode-action-buttons#38]
Add option for terminal - 'silent', which would not show Terminal window or just hide Terminal after the command execution.

P.S. Thanks! Great Extension! :-)

**Comment by holykiller** [comment]
Is there a way to have global commands and local commands? loaded at the same time?

**Comment by the-moka-pot** [comment]
As of now, you may chain the shell commands to hide the Terminal after the command executes.

### Exit post execution
`"command": "my-fancy-command && exit"`

It would be nice to see silent execution, and errors in notification toast. 🙂

**Comment by lisunovdv** [comment]
resolved: `"command": "my-fancy-command && exit"`
