### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by 3cees** [seunlanlege/vscode-action-buttons#4]
Hi,

when I click ctl+shift+p and click "Refresh Action Buttons", npthing happens. No buttons show up.
What can I do?

Many Thanks,
Lars

**Comment by SeunLanLege** [comment]
can i see your workspace settings?

**Comment by 3cees** [comment]
`{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "WpQrLogin"
		}
	],
	"settings": {}
}`

**Comment by 3cees** [comment]
How should it look like?

**Comment by SeunLanLege** [comment]
```
{
// other fields
    "run": {
   	 "defaultColor": "#ff0034", // Can also use string color names.
   	 "commands": [
   		 {
   			 "name": "Run Cargo", // Name of the action as you'll see it in the status bar
   			 "color": "green", // this overrides defaultColor
   			 "command": "cargo run", // This is executed in the terminal.
   		 },
   		 {
   			 "name": "Build Cargo",
   			 "color": "green",
   			 "command": "cargo build",
   		 }
   	 ]
    }```

**Comment by 3cees** [comment]
can you show me, how it has to like like in the settings file with my settings, I posted?
Do I have to place it in: a) user settings b) Workspace settings, or  c) ProjectName Settings?
Sorry, I'm new to Vs Code. ;(

**Comment by SeunLanLege** [comment]
replace your *workspace* settings with this.

```
{
  "folders":[
    {
      "path":"."
    },
    {
      "path":"WpQrLogin"
    }
  ],
  "settings":{

  },
  "run":{
    "defaultColor":"#ff0034",
    "commands":[
      {
        "name":"Run Cargo",
        "color":"green",
        "command":"cargo run"
      },
      {
        "name":"Build Cargo",
        "color":"green",
        "command":"cargo build"
      }
    ]
  }
}
```

**Comment by 3cees** [comment]
I get an error then:
Unknown Workspace configuration property and "run" is underlined.
The buttons do not apear.

**Comment by SeunLanLege** [comment]
disregard the warning, now refresh action buttons.

**Comment by 3cees** [comment]
i did. nothing happens.

**Comment by SeunLanLege** [comment]
did you try restarting vscode?

**Comment by 3cees** [comment]
Yes. I also created a ne workspace.

**Comment by HMubaireek** [comment]
Same issue here.

**Comment by jorgermiranda** [comment]
Same issue! :-(

**Comment by seunlanlege** [comment]
I've been very busy, but will try to properly look into this issue tonight

**Comment by NachtmahrEDM** [comment]
I still have that problem with my project.

**Comment by Marcosaurios** [comment]
Same problem here D: nothing happens when `CTRL+SHIFT+P`

**Comment by seunlanlege** [comment]
I've added a default `Refresh Action Buttons` in the status bar that will handle refreshing your action buttons after modifying the config.

the new config key is `actionButton` in your workspace settings.
