### ISSUE TITLE
Run tasks

### ISSUE THREAD

**Issue by bpatram** [seunlanlege/vscode-action-buttons#6]
To better integrate into VSCode it would be great to be able to kick off a specific task (https://code.visualstudio.com/docs/editor/tasks) in addition to one off commands.

**Comment by seunlanlege** [comment]
yeah this would require reading vscode's task list, not sure if such an api exists but if it does PR's welcome.

**Comment by bpatram** [comment]
Hello, thank you for responding! I've since found an extension which does exactly what I needed:

https://github.com/actboy168/vscode-tasks
https://marketplace.visualstudio.com/items?itemName=actboy168.tasks

That extension author seems to have figured it out how to add buttons for tasks. Of course, that extension does not allow for arbitrary commands to be run outside of tasks.json like this extension offers :)
