### ISSUE TITLE
singleInstance no longer works in v 1.2.0

### ISSUE THREAD

**Issue by mbenkmann** [seunlanlege/vscode-action-buttons#60]
Just updated to v 1.2.0 of ActionButtons and buttons with singleInstance:true only work once. The 2nd time I use the button I get and error popup "Running the contributed command: 'extension.Clean' failed." where Clean ist the name of the button. The command in question is simple call to make.

                "cwd": "${workspaceFolder}",    
                "name": "Clean",
                "color": "white",
                "singleInstance": true, 
                "command": "make -C arm clean",

**Comment by seunlanlege** [comment]
published v1.2.1

**Comment by ahehn** [comment]
Thank you!! 🥳
