### ISSUE TITLE
Button Doesn't Work Again After Run

### ISSUE THREAD

**Issue by mkormendy** [seunlanlege/vscode-action-buttons#76]
I have 5 action buttons set up, they work on the first time clicked.
After that the specific button clicked does not work anymore.

The only way to get them to work again is to reload the action buttons.

**Comment by gchmiel** [comment]
Hi @mkormendy,
I was struggling with the same problem. If you haven't found solution for this, here you go:
Just add "singleInstance": true, to each button you want to work each time you press it.

Hope this will help you or someone else who wonders why buttons work only once ;)

**Comment by mkormendy** [comment]
@gchmiel thank you for this .. it appears like it is working! Thanks!
